<a href="https://colab.research.google.com/github/BioBarto/BioinformatykaRoslin2021/blob/main/Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("hello word")

hello word

## Wczytanie zbioru danych z u≈ºyciem biblioteki pandas
###OUTPUT: 
data_pd

In [22]:
import pandas as pd
path_to_data = "https://raw.githubusercontent.com/BioBarto/BioinformatykaRoslin2021/main/data_all.txt"
data_pd = pd.read_csv(path_to_data)

In [23]:
data.head()

   grain_yield  pht_height  Heading_Date  ...  SNP_2316  SNP_2317  SNP_2318
0         4869          78          57.5  ...         1        -1        -1
1         4621          74          56.0  ...         1        -1         1
2         4557          66          58.0  ...         1        -1         1
3         5484          77          59.0  ...         1        -1        -1
4         4641          69          55.5  ...         1        -1        -1

[5 rows x 2321 columns]

## Wczytanie zbioru danych z u≈ºyciem biblioteki import.url
###OUTPUT: 
data_url

In [27]:
import urllib.request  # the lib that handles the url stuff
url = "https://raw.githubusercontent.com/BioBarto/BioinformatykaRoslin2021/main/data_all.txt"
file = urllib.request.urlopen(url)

data_url = []
for line in urllib.request.urlopen(url):
    data_url.append(line.decode('utf-8'))

In [28]:
data.head()

   grain_yield  pht_height  Heading_Date  ...  SNP_2316  SNP_2317  SNP_2318
0         4869          78          57.5  ...         1        -1        -1
1         4621          74          56.0  ...         1        -1         1
2         4557          66          58.0  ...         1        -1         1
3         5484          77          59.0  ...         1        -1        -1
4         4641          69          55.5  ...         1        -1        -1

[5 rows x 2321 columns]

## KOD potrzebny do ANALIZY zbioru

In [32]:
#R√≥≈ºnice pomiƒôdzy data_url / data_pd

print(type(data_url))
print(type(data_pd))

<class 'list'>
<class 'pandas.core.frame.DataFrame'>

In [35]:
#Okre≈õlam zmienƒÖ data - jako listƒô (nie jako macierz z biblioteki Panda)
data = data_pd